package org.wut;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: AuxSkill <br>
 * @version generated on Thu May 21 22:15:53 CEST 2015 by Pawel
 */

public interface AuxSkill extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasSkill
     */
     
    /**
     * Gets all property values for the hasSkill property.<p>
     * 
     * @returns a collection of values for the hasSkill property.
     */
    Collection<? extends Skill> getHasSkill();

    /**
     * Checks if the class has a hasSkill property value.<p>
     * 
     * @return true if there is a hasSkill property value.
     */
    boolean hasHasSkill();

    /**
     * Adds a hasSkill property value.<p>
     * 
     * @param newHasSkill the hasSkill property value to be added
     */
    void addHasSkill(Skill newHasSkill);

    /**
     * Removes a hasSkill property value.<p>
     * 
     * @param oldHasSkill the hasSkill property value to be removed.
     */
    void removeHasSkill(Skill oldHasSkill);


    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasDescription
     */
     
    /**
     * Gets all property values for the hasDescription property.<p>
     * 
     * @returns a collection of values for the hasDescription property.
     */
    Collection<? extends String> getHasDescription();

    /**
     * Checks if the class has a hasDescription property value.<p>
     * 
     * @return true if there is a hasDescription property value.
     */
    boolean hasHasDescription();

    /**
     * Adds a hasDescription property value.<p>
     * 
     * @param newHasDescription the hasDescription property value to be added
     */
    void addHasDescription(String newHasDescription);

    /**
     * Removes a hasDescription property value.<p>
     * 
     * @param oldHasDescription the hasDescription property value to be removed.
     */
    void removeHasDescription(String oldHasDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasLevel
     */
     
    /**
     * Gets all property values for the hasLevel property.<p>
     * 
     * @returns a collection of values for the hasLevel property.
     */
    Collection<? extends Integer> getHasLevel();

    /**
     * Checks if the class has a hasLevel property value.<p>
     * 
     * @return true if there is a hasLevel property value.
     */
    boolean hasHasLevel();

    /**
     * Adds a hasLevel property value.<p>
     * 
     * @param newHasLevel the hasLevel property value to be added
     */
    void addHasLevel(Integer newHasLevel);

    /**
     * Removes a hasLevel property value.<p>
     * 
     * @param oldHasLevel the hasLevel property value to be removed.
     */
    void removeHasLevel(Integer oldHasLevel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
