package org.wut;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Person <br>
 * @version generated on Thu May 21 22:15:53 CEST 2015 by Pawel
 */

public interface Person extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasAuxSkill
     */
     
    /**
     * Gets all property values for the hasAuxSkill property.<p>
     * 
     * @returns a collection of values for the hasAuxSkill property.
     */
    Collection<? extends AuxSkill> getHasAuxSkill();

    /**
     * Checks if the class has a hasAuxSkill property value.<p>
     * 
     * @return true if there is a hasAuxSkill property value.
     */
    boolean hasHasAuxSkill();

    /**
     * Adds a hasAuxSkill property value.<p>
     * 
     * @param newHasAuxSkill the hasAuxSkill property value to be added
     */
    void addHasAuxSkill(AuxSkill newHasAuxSkill);

    /**
     * Removes a hasAuxSkill property value.<p>
     * 
     * @param oldHasAuxSkill the hasAuxSkill property value to be removed.
     */
    void removeHasAuxSkill(AuxSkill oldHasAuxSkill);


    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasDescription
     */
     
    /**
     * Gets all property values for the hasDescription property.<p>
     * 
     * @returns a collection of values for the hasDescription property.
     */
    Collection<? extends String> getHasDescription();

    /**
     * Checks if the class has a hasDescription property value.<p>
     * 
     * @return true if there is a hasDescription property value.
     */
    boolean hasHasDescription();

    /**
     * Adds a hasDescription property value.<p>
     * 
     * @param newHasDescription the hasDescription property value to be added
     */
    void addHasDescription(String newHasDescription);

    /**
     * Removes a hasDescription property value.<p>
     * 
     * @param oldHasDescription the hasDescription property value to be removed.
     */
    void removeHasDescription(String oldHasDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasEmail
     */
     
    /**
     * Gets all property values for the hasEmail property.<p>
     * 
     * @returns a collection of values for the hasEmail property.
     */
    Collection<? extends String> getHasEmail();

    /**
     * Checks if the class has a hasEmail property value.<p>
     * 
     * @return true if there is a hasEmail property value.
     */
    boolean hasHasEmail();

    /**
     * Adds a hasEmail property value.<p>
     * 
     * @param newHasEmail the hasEmail property value to be added
     */
    void addHasEmail(String newHasEmail);

    /**
     * Removes a hasEmail property value.<p>
     * 
     * @param oldHasEmail the hasEmail property value to be removed.
     */
    void removeHasEmail(String oldHasEmail);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
