package org.wut;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu May 21 22:15:53 CEST 2015 by Pawel
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#AuxSkill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUXSKILL.<p>
     * 
     */
    public static final OWLClass CLASS_AUXSKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#AuxSkill"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#BackEnd
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BACKEND.<p>
     * 
     */
    public static final OWLClass CLASS_BACKEND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#BackEnd"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Certificate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CERTIFICATE.<p>
     * 
     */
    public static final OWLClass CLASS_CERTIFICATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Certificate"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Course
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COURSE.<p>
     * 
     */
    public static final OWLClass CLASS_COURSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Course"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Database
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATABASE.<p>
     * 
     */
    public static final OWLClass CLASS_DATABASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Database"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Design
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DESIGN.<p>
     * 
     */
    public static final OWLClass CLASS_DESIGN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Design"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Developing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVELOPING.<p>
     * 
     */
    public static final OWLClass CLASS_DEVELOPING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Developing"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#FrontEnd
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRONTEND.<p>
     * 
     */
    public static final OWLClass CLASS_FRONTEND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#FrontEnd"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Job
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JOB.<p>
     * 
     */
    public static final OWLClass CLASS_JOB = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Job"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#MobileTechnology
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOBILETECHNOLOGY.<p>
     * 
     */
    public static final OWLClass CLASS_MOBILETECHNOLOGY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#MobileTechnology"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#NetworkAdministration
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NETWORKADMINISTRATION.<p>
     * 
     */
    public static final OWLClass CLASS_NETWORKADMINISTRATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#NetworkAdministration"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#NoSQL
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOSQL.<p>
     * 
     */
    public static final OWLClass CLASS_NOSQL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#NoSQL"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#OnlineSchool
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONLINESCHOOL.<p>
     * 
     */
    public static final OWLClass CLASS_ONLINESCHOOL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#OnlineSchool"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Person"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Programmer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROGRAMMER.<p>
     * 
     */
    public static final OWLClass CLASS_PROGRAMMER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Programmer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Project
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Project"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#RelationalDatabase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RELATIONALDATABASE.<p>
     * 
     */
    public static final OWLClass CLASS_RELATIONALDATABASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#RelationalDatabase"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Skill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKILL.<p>
     * 
     */
    public static final OWLClass CLASS_SKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Skill"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Task
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TASK.<p>
     * 
     */
    public static final OWLClass CLASS_TASK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Task"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Testing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TESTING.<p>
     * 
     */
    public static final OWLClass CLASS_TESTING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Testing"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#Tutorial
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TUTORIAL.<p>
     * 
     */
    public static final OWLClass CLASS_TUTORIAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#Tutorial"));

    /* ***************************************************
     * Class http://www.semanticweb.org/pawel/ontologies/workfinder#WebTechnology
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WEBTECHNOLOGY.<p>
     * 
     */
    public static final OWLClass CLASS_WEBTECHNOLOGY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#WebTechnology"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasAuxSkill
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASAUXSKILL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASAUXSKILL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasAuxSkill"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasCertificate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCERTIFICATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCERTIFICATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasCertificate"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasSkill
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSKILL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSKILL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasSkill"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasTask
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTASK = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasTask"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#isAssignedTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISASSIGNEDTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISASSIGNEDTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#isAssignedTo"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasDescription"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasEmail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEMAIL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasEmail"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasEndDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENDDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENDDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasEndDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasLevel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLEVEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasLevel"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasStartDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTARTDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTARTDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/pawel/ontologies/workfinder#hasStartDate"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
