package org.wut.impl;

import org.wut.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAuxSkill <br>
 * @version generated on Thu May 21 22:15:53 CEST 2015 by Pawel
 */
public class DefaultAuxSkill extends WrappedIndividualImpl implements AuxSkill {

    public DefaultAuxSkill(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasSkill
     */
     
    public Collection<? extends Skill> getHasSkill() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSKILL,
                                               DefaultSkill.class);
    }

    public boolean hasHasSkill() {
	   return !getHasSkill().isEmpty();
    }

    public void addHasSkill(Skill newHasSkill) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSKILL,
                                       newHasSkill);
    }

    public void removeHasSkill(Skill oldHasSkill) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSKILL,
                                          oldHasSkill);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasDescription
     */
     
    public Collection<? extends String> getHasDescription() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDESCRIPTION, String.class);
    }

    public boolean hasHasDescription() {
		return !getHasDescription().isEmpty();
    }

    public void addHasDescription(String newHasDescription) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDESCRIPTION, newHasDescription);
    }

    public void removeHasDescription(String oldHasDescription) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDESCRIPTION, oldHasDescription);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/pawel/ontologies/workfinder#hasLevel
     */
     
    public Collection<? extends Integer> getHasLevel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEVEL, Integer.class);
    }

    public boolean hasHasLevel() {
		return !getHasLevel().isEmpty();
    }

    public void addHasLevel(Integer newHasLevel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEVEL, newHasLevel);
    }

    public void removeHasLevel(Integer oldHasLevel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEVEL, oldHasLevel);
    }


}
